#!/bin/sh
set -e

### BEGIN INIT INFO
# Provides:             teamcity
# Required-Start:       $local_fs $remote_fs $network $time
# Required-Stop:        $local_fs $remote_fs $network $time
# Should-Start:         $syslog
# Should-Stop:          $syslog
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    TeamCity server and agent star-stop script
### END INIT INFO

TEAMCITY_DIR=/home/ubuntu/TeamCity
TEAMCITY_USER=teamcity
TEAMCITY_AGENT_DIR=${TEAMCITY_DIR}/buildAgent

case $1 in
  start)
    echo "Starting TeamCity"
    start-stop-daemon --start  -c ${TEAMCITY_USER} --exec ${TEAMCITY_DIR}/bin/teamcity-server.sh start
    start-stop-daemon --start  -c ${TEAMCITY_USER} --exec ${TEAMCITY_AGENT_DIR}/bin/agent.sh start
    ;;
  stop)
    echo "Stopping TeamCity"
    start-stop-daemon --start -c ${TEAMCITY_USER} --exec ${TEAMCITY_DIR}/bin/teamcity-server.sh stop
    start-stop-daemon --start  -c ${TEAMCITY_USER} --exec ${TEAMCITY_AGENT_DIR}/bin/agent.sh stop
    ;;
  restart)
    echo "Restarting TeamCity"
    start-stop-daemon --start  -c ${TEAMCITY_USER} --exec ${TEAMCITY_DIR}/bin/teamcity-server.sh stop
    start-stop-daemon --start  -c ${TEAMCITY_USER} --exec ${TEAMCITY_AGENT_DIR}/bin/agent.sh stop
    start-stop-daemon --start  -c ${TEAMCITY_USER} --exec ${TEAMCITY_DIR}/bin/teamcity-server.sh start
    start-stop-daemon --start  -c ${TEAMCITY_USER} --exec ${TEAMCITY_AGENT_DIR}/bin/agent.sh start
    ;;
  *)
    echo "Usage: /etc/init.d/teamcity {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
